FROM node:18-alpine as builder
WORKDIR /app
COPY package*.json ./
COPY frontend ./frontend
RUN npm install
RUN cd frontend && npm run build

FROM nginx:alpine
COPY --from=builder /app/frontend/dist /usr/share/nginx/html
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
